### ISSUE TITLE
Fix the `develop` branch

### ISSUE THREAD

**Issue by konradkonrad** [ethereum/pyethereum#373]
Right now, `develop` builds look dire. In order to get a green light again, I think (at least) the following steps need to be done:
- [x] merge #372 to fix the test-fixtures
- [x] rebase and merge #371 
- [x] rebase and merge #369 
- [x] identify and fix outstanding bugs recently introduced
- [x] restart from last working develop and cherry-pick good commits into [`fix-develop`](https://github.com/ethereum/pyethereum/tree/fix-develop)
- [x] move new feature commits/EIPs into branches PRs of their own, based on `fix-develop`, so they can be fixed/merged atomically; create PRs against `fix-develop`:
  - [x] ~~EIP 90 #379~~ metropolis_config #383 :heavy_check_mark: 
  - [x] EIP 86 #377 :heavy_check_mark: 
  - [x] EIP 98 #378  :heavy_check_mark: 
  - [x] EIP 100 #380 :heavy_check_mark: 
  - [x] general py3 stuff  #386 :heavy_check_mark: 
  - [x] DAO HF ~~# 382~~ #387  :grey_question: (no tests for that)
  - [x] VMExt ~~# 384~~ #388  :cry: 
  - [x] EIP 97 ~~# 381~~  #389 :cry: 
- [x] **?** force push `fix-develop` onto `develop` afterwards (

> Q: is there a nicer way? 
```
git checkout develop
git checkout origin/fix-develop .
git checkout develop
git commit  # ae2498ac7f907dddc819185c013e9931228704d3
git merge origin/fix-develop   # 025d43b7377a781be2e6d6c0ead5a7fb59bb6135
```

^--- thanks @ulope !

Please everyone involved in above PRs organize through this issue, so we have a happy travis guy and a :white_check_mark: again soon!

**Comment by pipermerriam** [comment]
On it boss!

**Comment by pipermerriam** [comment]
#369 rebased

**Comment by pipermerriam** [comment]
#370 is an issue.  Was there a different Pull Request you were meaning to point to?

**Comment by konradkonrad** [comment]
> #370 is an issue. Was there a different Pull Request you were meaning to point to?
no :)

**Comment by konradkonrad** [comment]
I'm working on this in the `fix-develop` branch

**Comment by konradkonrad** [comment]
done!

#387 #388 #389 stay open until their tests are fixed, but now they are against `develop`.
